--------------------------------------------------------------------------------
-- Message Bus -- Tag based message router
--------------------------------------------------------------------------------
local M = {}

---@class BusInitOpt
---@field cache_max? integer Maximum queued messages before dropping new ones

---@alias BusKey string
---@alias BusSource string
---@alias BusMessageMode "new"|"replace"|"append"|"clear"

---@class Message
---@field event_id integer Unique event sequence generated by this bus
---@field key? BusKey Stable logical message key; same key means same logical message
---@field mode BusMessageMode How this event should affect existing rendered state
---@field tag string Routing tag, e.g. "msg.show.echomsg", "notify"
---@field level integer vim.log.levels.*
---@field source BusSource Message source, e.g. "nvim.ui", "vim.notify", "lsp", "bus"
---@field source_id integer|string|nil Opaque source-native id; keep original type
---@field timestamp integer vim.uv.now()
---@field text? string Flattened plain text for simple renderers
---@field content any Structured payload; renderers decide how to use it
---@field meta table? Source-specific metadata, opaque to the bus

---@class BusEmitOpt
---@field key? BusKey Stable logical message key; same key means same logical message
---@field mode? BusMessageMode Defaults to "new"
---@field tag string Routing tag for subscriber matching
---@field level? integer Defaults to vim.log.levels.INFO
---@field source? BusSource Defaults to "user"
---@field source_id? integer|string|nil Opaque source-native id, e.g. Nvim msg_show id
---@field text? string Flattened plain text for simple renderers
---@field content any Structured payload; renderers decide how to use it
---@field meta? table Source-specific metadata, opaque to the bus

---@class BusSubscriber
---@field id string
---@field full_match table<string, boolean> Exact strings to match interested tags in O(1)
---@field prefix_match string[] Prefixes to match interested tags in O(n)
---@field fuzzy_match string[] Lua patterns to match interested tags in O(n)
---@field min_level integer Minimum vim.log.levels.* accepted by this subscriber
---@field handler fun(msg: Message): boolean? Return true to stop further propagation

---@class BusSubscriberInterestedTagDecl
---@field exact? string[] O(1) hash lookup
---@field prefix? string[] O(n) startswith
---@field fuzzy? string[] O(n) Lua pattern match

---@alias BusSubscriberMessageConsumer fun(msg: Message): boolean?

---@class BusSubscriberDecl
---@field id string
---@field interested BusSubscriberInterestedTagDecl
---@field min_level integer
---@field handler BusSubscriberMessageConsumer

---@class BusOpt
---@field subscribers? BusSubscriberDecl[]
---@field bus_backend? string Subscriber id used to receive bus internal logs; required by start()

---@class BusStat
---@field IsInitialized boolean
---@field Ready boolean Cache messages when bus is not ready yet
---@field Queue Message[] FIFO message buffer
---@field Busy boolean Is dispatching a message right now?
---@field queue_end integer Current flush cursor inside Queue
---@field flush_depth integer Nested flush depth guard
---@field Dropped integer Number of dropped queued messages due to cache_max

---@type BusInitOpt
local BUS_INIT_OPT_DEFAULT = {
    cache_max = 2048,
}

---@type BusOpt
local BUS_OPT_DEFAULT = {
    subscribers = {},
}

---@type BusInitOpt
local InitOpt = vim.deepcopy(BUS_INIT_OPT_DEFAULT)

---@type BusOpt
local Opt = vim.deepcopy(BUS_OPT_DEFAULT)

---@type table<string, BusSubscriber>
local Subscribers = {}

---@type BusStat
-- Queue messages until the bus is ready, then dispatch them in order.
local Stat = {
    IsInitialized = false,
    Ready = false,
    Queue = {},
    Busy = false,
    queue_end = 1,
    flush_depth = 0,
    Dropped = 0,
}

local NextEventId = 0

local VALID_MODE = {
    new = true,
    replace = true,
    append = true,
    clear = true,
}

local function next_event_id()
    NextEventId = NextEventId + 1
    return NextEventId
end

---@param namespace string
---@param raw_id integer|string
---@return string
function M.compose_key(namespace, raw_id)
    assert(type(namespace) == 'string' and namespace ~= '', 'compose_key(namespace, raw_id): namespace must be a non-empty string')
    local raw_type = type(raw_id)
    assert(raw_type == 'string' or raw_type == 'number', 'compose_key(namespace, raw_id): raw_id must be a string or number')
    return namespace .. ':' .. tostring(raw_id)
end

---@param opts BusEmitOpt
---@return Message
-- Normalize emit options into a concrete bus message.
local function build_msg(opts)
    assert(type(opts) == 'table', 'Bus.emit(opts): opts must be a table')
    assert(type(opts.tag) == 'string' and opts.tag ~= '', 'Bus.emit(opts): opts.tag must be a non-empty string')

    local mode = opts.mode or 'new'
    assert(VALID_MODE[mode] == true, 'Bus.emit(opts): opts.mode must be one of new|replace|append|clear')

    if opts.key ~= nil then
        assert(type(opts.key) == 'string' and opts.key ~= '', 'Bus.emit(opts): opts.key must be a non-empty string when provided')
    end

    local source = opts.source or 'user'
    assert(type(source) == 'string' and source ~= '', 'Bus.emit(opts): opts.source must be a non-empty string when provided')

    local source_id = opts.source_id
    if source_id ~= nil then
        local source_id_type = type(source_id)
        assert(source_id_type == 'string' or source_id_type == 'number', 'Bus.emit(opts): opts.source_id must be a string or number when provided')
    end

    local level = opts.level or vim.log.levels.INFO
    assert(type(level) == 'number', 'Bus.emit(opts): opts.level must be a number when provided')

    local text = opts.text
    if text ~= nil then
        assert(type(text) == 'string', 'Bus.emit(opts): opts.text must be a string when provided')
    elseif type(opts.content) == 'string' then
        text = opts.content
    end

    ---@type Message
    return {
        event_id = next_event_id(),
        key = opts.key,
        mode = mode,
        tag = opts.tag,
        level = level,
        source = source,
        source_id = source_id,
        timestamp = vim.uv.now(),
        text = text,
        content = opts.content,
        meta = opts.meta,
    }
end

---@param msg Message
---@return boolean
-- Keep the queue bounded so early bursts do not grow without limit.
local function enqueue_or_drop(msg)
    if #Stat.Queue < InitOpt.cache_max then
        table.insert(Stat.Queue, msg)
        return true
    end
    Stat.Dropped = Stat.Dropped + 1
    return false
end

local function clear_queue()
    Stat.Queue = {}
    Stat.queue_end = 1
end

local function maybe_report_dropped()
    if Stat.Dropped <= 0 then
        return
    end
    local dropped = Stat.Dropped
    Stat.Dropped = 0
    local backend = Opt.bus_backend and Subscribers[Opt.bus_backend]
    if not backend or type(backend.handler) ~= 'function' then
        return
    end
    local msg = build_msg {
        tag = 'bus',
        level = vim.log.levels.WARN,
        source = 'bus',
        text = string.format('[Queue] dropped %d message(s) because cache_max=%d was reached', dropped, InitOpt.cache_max),
        content = string.format('[Queue] dropped %d message(s) because cache_max=%d was reached', dropped, InitOpt.cache_max),
        meta = {
            dropped = dropped,
            cache_max = InitOpt.cache_max,
        },
    }
    if msg.level < (backend.min_level or vim.log.levels.TRACE) then
        return
    end
    pcall(backend.handler, msg)
end

-- Pipe internal message to the configured bus backend directly.
---@param msg string
---@param lvl? integer
local function _bus_log(msg, lvl)
    local backend = Opt.bus_backend and Subscribers[Opt.bus_backend]
    if not backend or type(backend.handler) ~= 'function' then
        return
    end

    local built_msg = build_msg {
        tag = 'bus',
        level = lvl or vim.log.levels.INFO,
        source = 'bus',
        text = msg,
        content = msg,
        meta = { internal = true },
    }

    if built_msg.level < (backend.min_level or vim.log.levels.TRACE) then
        return
    end

    pcall(backend.handler, built_msg)
end

---@param backend BusSubscriber
---@param tag string
---@return boolean
local function matches(backend, tag)
    if backend.full_match[tag] then
        return true
    end

    for _, prefix in ipairs(backend.prefix_match) do
        if vim.startswith(tag, prefix) then
            return true
        end
    end

    for _, pattern in ipairs(backend.fuzzy_match) do
        if tag:match(pattern) then
            return true
        end
    end

    return false
end

---@param msg Message
local function bus_dispatch(msg)
    if Stat.Busy then
        enqueue_or_drop(msg)
        return
    end

    Stat.Busy = true

    for _, backend in pairs(Subscribers) do
        if msg.level >= (backend.min_level or vim.log.levels.TRACE) and matches(backend, msg.tag) then
            if type(backend.handler) == 'function' then
                local handler_ok, should_stop = pcall(backend.handler, msg)
                if not handler_ok then
                    _bus_log(string.format("[Dispatcher] Handler '%s' panic for: '%s'", backend.id, should_stop), vim.log.levels.ERROR)
                elseif should_stop == true then
                    break
                end
            end
        end
    end

    Stat.Busy = false
end

local FLUSH_MAX_DEPTH = 4

---@param id string
---@param interested BusSubscriberInterestedTagDecl
---@param min_level integer
---@param handler BusSubscriberMessageConsumer
---@return boolean, string?
function M.register_subscriber(id, interested, min_level, handler)
    if Subscribers[id] then
        return false, 'Subscriber `' .. id .. '` already exists'
    end

    assert(type(id) == 'string' and id ~= '', 'register_subscriber(id, ...): id must be a non-empty string')
    assert(type(handler) == 'function', 'register_subscriber(..., handler): handler must be a function')

    local set = {}
    interested = interested or {}

    for _, candidate in ipairs(interested.exact or {}) do
        set[candidate] = true
    end

    Subscribers[id] = {
        id = id,
        prefix_match = interested.prefix or {},
        full_match = set,
        fuzzy_match = interested.fuzzy or {},
        min_level = min_level or vim.log.levels.TRACE,
        handler = handler,
    }
    return true
end

---@param id string
function M.unsubscribe(id)
    Subscribers[id] = nil
end

function M.flush_queue()
    if not Stat.Ready or Stat.Busy then
        _bus_log(
            string.format('[Queue Flusher] rescheduled (ready=%s, busy=%s, queued=%d)', tostring(Stat.Ready), tostring(Stat.Busy), #Stat.Queue),
            vim.log.levels.DEBUG
        )
        vim.schedule(M.flush_queue)
        return
    end

    if Stat.flush_depth >= FLUSH_MAX_DEPTH then
        _bus_log(
            string.format('[Queue Flusher] flush_queue exceeded max depth (%d), queue dropped (%d msgs)', FLUSH_MAX_DEPTH, #Stat.Queue),
            vim.log.levels.ERROR
        )
        clear_queue()
        return
    end

    local batch_start = Stat.queue_end
    local batch_end = #Stat.Queue
    if batch_start > batch_end then
        _bus_log('[Queue Flusher] queue already drained', vim.log.levels.DEBUG)
        clear_queue()
        return
    end

    Stat.flush_depth = Stat.flush_depth + 1
    maybe_report_dropped()
    _bus_log(
        string.format('[Queue Flusher] flushing batch start=%d end=%d depth=%d total=%d', batch_start, batch_end, Stat.flush_depth, #Stat.Queue),
        vim.log.levels.DEBUG
    )

    for i = batch_start, batch_end do
        local msg = Stat.Queue[i]
        Stat.queue_end = i + 1
        local ok, err = pcall(bus_dispatch, msg)
        if not ok then
            Stat.Busy = false
            _bus_log('[Queue Flusher] dispatcher panic for `' .. err .. '`', vim.log.levels.ERROR)
        end
    end

    if #Stat.Queue > batch_end then
        _bus_log(string.format('[Queue Flusher] batch complete, %d new msg(s) queued during flush', #Stat.Queue - batch_end), vim.log.levels.DEBUG)
        M.flush_queue()
    else
        _bus_log(string.format('[Queue Flusher] batch complete, queue drained (%d msg(s))', batch_end - batch_start + 1), vim.log.levels.DEBUG)
        clear_queue()
    end

    Stat.flush_depth = Stat.flush_depth - 1
end

--- Emit a message to the bus.
---
--- Recommended Nvim msg_show mapping:
--- - source = "nvim.ui"
--- - source_id = <raw msg_show id>
--- - key = Bus.compose_key("nvim.msg", source_id)
---@param opts BusEmitOpt
---@return integer event_id
function M.emit(opts)
    local msg = build_msg(opts)
    local event_id = msg.event_id

    if not Stat.Ready or Stat.Busy then
        enqueue_or_drop(msg)
        return event_id
    end

    local ok, err = pcall(bus_dispatch, msg)
    if not ok then
        Stat.Busy = false
        _bus_log('[Emitter] dispatcher panic for `' .. err .. '`', vim.log.levels.ERROR)
    end

    if Stat.Ready and #Stat.Queue > 0 then
        vim.schedule(M.flush_queue)
    end

    return event_id
end

--- Stage 2: register configured subscribers and start dispatching queued messages.
---@param opts BusOpt|nil
function M.start(opts)
    if not Stat.IsInitialized then
        M.init()
    end

    if Stat.Ready then
        _bus_log('Should not start bus more than once!', vim.log.levels.WARN)
        return
    end

    Opt = vim.tbl_extend('force', Opt, opts or {})

    for _, decl in ipairs(Opt.subscribers or {}) do
        local ok, err = M.register_subscriber(decl.id, decl.interested, decl.min_level, decl.handler)
        assert(ok, err)
    end

    assert(type(Opt.bus_backend) == 'string' and Subscribers[Opt.bus_backend], 'Bus.start(opts): opts.bus_backend must name an existing subscriber')

    Stat.Ready = true
    M.flush_queue()
end

--- Stage 1: initialize bus and allow messages to be queued before start().
---@param opts BusInitOpt|nil
function M.init(opts)
    if Stat.IsInitialized then
        return
    end
    InitOpt = vim.tbl_extend('force', InitOpt, opts or {})
    Stat.IsInitialized = true
end

return M
